"""Setup script for Weights & Biases integration.

This script helps configure W&B for CNM-BERT training with proper
project setup, entity configuration, and metadata tracking.
"""

import argparse
import os
import sys
from pathlib import Path

try:
    import wandb
except ImportError:
    print("Error: wandb package not installed")
    print("Install with: pip install wandb")
    sys.exit(1)


def setup_wandb(
    project_name: str = "cnm-bert",
    entity: str = None,
    tags: list = None,
    notes: str = None,
):
    """Setup Weights & Biases for CNM-BERT training.

    Args:
        project_name: W&B project name
        entity: W&B entity (username or team)
        tags: List of tags for organizing runs
        notes: Description of the project
    """
    print("=" * 70)
    print("Weights & Biases Setup for CNM-BERT")
    print("=" * 70)
    print()

    # Check if already logged in
    try:
        api = wandb.Api()
        current_user = api.viewer
        print(f"✓ Already logged in as: {current_user.username}")
        print()
    except Exception:
        print("W&B login required.")
        print()
        print("Please follow these steps:")
        print("1. Sign up at https://wandb.ai (if you haven't already)")
        print("2. Get your API key from https://wandb.ai/authorize")
        print("3. Enter it below when prompted")
        print()

        # Login
        wandb.login()
        print()
        print("✓ Login successful!")
        print()

    # Get entity if not provided
    if entity is None:
        api = wandb.Api()
        entity = api.default_entity
        print(f"Using default entity: {entity}")

    # Default tags
    if tags is None:
        tags = [
            "cnm-bert",
            "chinese-nlp",
            "pre-training",
            "acl-2026",
            "8x-h100",
        ]

    # Default notes
    if notes is None:
        notes = """
CNM-BERT Pre-training: Integrating Orthographic Compositionality via IDS

This project implements a novel Chinese PLM that explicitly models character
composition using Ideographic Description Sequences (IDS). The model uses a
dual-path encoder combining standard BERT embeddings with Tree-MLP structural
encodings for improved semantic representation.

Target: ACL 2026 Main Conference
Hardware: 8x NVIDIA H100 80GB
Training: ~1M steps on Wikipedia-zh (~100M sentences)
"""

    # Create config file
    config_path = Path.home() / ".wandb_config"
    config_content = f"""# Weights & Biases Configuration for CNM-BERT
# Auto-generated by setup_wandb.py

export WANDB_PROJECT="{project_name}"
export WANDB_ENTITY="{entity}"
export WANDB_TAGS="{','.join(tags)}"
export WANDB_NOTES="{notes.strip()}"
export WANDB_LOG_MODEL="checkpoint"  # Log model checkpoints
export WANDB_WATCH="all"  # Watch all parameters
"""

    with open(config_path, "w") as f:
        f.write(config_content)

    print()
    print("=" * 70)
    print("W&B Configuration")
    print("=" * 70)
    print(f"Project: {project_name}")
    print(f"Entity: {entity}")
    print(f"Tags: {', '.join(tags)}")
    print()
    print(f"Configuration saved to: {config_path}")
    print()
    print("To use this configuration in your shell:")
    print(f"  source {config_path}")
    print()

    # Add to bashrc if user wants
    bashrc_path = Path.home() / ".bashrc"
    if bashrc_path.exists():
        response = input("Add W&B config to ~/.bashrc? [y/N]: ").strip().lower()
        if response == 'y':
            with open(bashrc_path, "a") as f:
                f.write(f"\n# Weights & Biases for CNM-BERT\n")
                f.write(f"source {config_path}\n")
            print("✓ Added to ~/.bashrc")
            print("  Run 'source ~/.bashrc' or restart shell to activate")
            print()

    # Test W&B connection
    print("Testing W&B connection...")
    try:
        # Initialize a test run
        run = wandb.init(
            project=project_name,
            entity=entity,
            tags=tags,
            notes=notes,
            name="test-connection",
            config={
                "test": True,
                "model": "cnm-bert",
                "hardware": "8x-h100",
            }
        )

        # Log a test metric
        wandb.log({"test_metric": 1.0})

        # Finish run
        wandb.finish()

        print("✓ W&B connection test successful!")
        print()
    except Exception as e:
        print(f"✗ W&B connection test failed: {e}")
        print("Please check your internet connection and try again")
        sys.exit(1)

    print("=" * 70)
    print("Setup Complete!")
    print("=" * 70)
    print()
    print("Your training runs will now automatically sync to:")
    print(f"  https://wandb.ai/{entity}/{project_name}")
    print()
    print("During training, you can monitor:")
    print("  - Real-time loss curves")
    print("  - Learning rate schedule")
    print("  - GPU utilization")
    print("  - System metrics (memory, CPU, etc.)")
    print("  - Sample predictions")
    print("  - Model checkpoints")
    print()
    print("Happy training! 🚀")
    print()


def main():
    parser = argparse.ArgumentParser(
        description="Setup Weights & Biases for CNM-BERT"
    )
    parser.add_argument(
        "--project",
        type=str,
        default="cnm-bert",
        help="W&B project name (default: cnm-bert)"
    )
    parser.add_argument(
        "--entity",
        type=str,
        default=None,
        help="W&B entity (username or team)"
    )
    parser.add_argument(
        "--tags",
        nargs="+",
        default=None,
        help="Tags for organizing runs"
    )
    parser.add_argument(
        "--notes",
        type=str,
        default=None,
        help="Project description"
    )
    args = parser.parse_args()

    setup_wandb(
        project_name=args.project,
        entity=args.entity,
        tags=args.tags,
        notes=args.notes,
    )


if __name__ == "__main__":
    main()
